# -*- coding: utf-8 -*-
# backend/cartaos/utils/utils.py
import logging
from typing import List


class WarningCaptureHandler(logging.Handler):
    """
    Custom logging handler to capture log records into a list.

    This is used to capture warnings generated by pdfminer and pdf2image
    during the OCR step. Warnings are appended to the provided list.
    """

    def __init__(self, messages_list: List[str]):
        """
        Initializes the handler.

        Args:
            messages_list (List[str]): The list to which log messages will be appended.
        """
        super().__init__()
        self.messages_list: List[str] = messages_list

    def emit(self, record: logging.LogRecord) -> None:
        """Captures the formatted log message in the list."""
        self.messages_list.append(self.format(record))
